- name: Install AD-Domain-Services feature
  win_feature: 
    name: AD-Domain-Services
    include_management_tools: yes
    include_sub_features: yes
    state: present

- name: Install AD Controller
  win_domain: 
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: result

- name: Reboot upon created
  win_reboot:
  when: result.reboot_required

- name: List DCs in domain
  win_shell: "nltest /dclist:ad1.4ff1.example.opentlc.com"
  register: domain_list

- debug:
    var: domain_list
